# Generated by Django 3.2.6 on 2021-08-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='emp_name',
        ),
    ]
