# Generated by Django 3.2.6 on 2021-08-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_remove_employee_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='eemp_no',
            new_name='emp_no',
        ),
    ]
