# Generated by Django 3.2.6 on 2021-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0005_rename_eemp_no_salary_emp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='dept',
            field=models.CharField(default='Accountant', max_length=60),
            preserve_default=False,
        ),
    ]
