# Generated by Django 3.2.6 on 2021-08-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0006_salary_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='dept',
        ),
    ]
